name:        "GT Game Engine"
description: "GT Game Engine"

#url:         "http://mackron.github.io/gtgameengine"
url:         "http://localhost:4000"

paginate:    10

markdown:    rdiscount
permalink:   pretty
pygments:    true