name:        "GTGameEngine"
description: "GTGameEngine"
#baseurl:     "http://mackron.github.io/GTGameEngine"
baseurl:     ""

paginate:    10

markdown:    rdiscount
permalink:   pretty
pygments:    true
